# Generated by Django 3.1.8 on 2021-04-28 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('home', '0004_auto_20210428_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='cta_btn_link',
            field=models.ForeignKey(blank=True, help_text='Internal page link to send the user to when clicking CTA button.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_btn_text',
            field=models.CharField(blank=True, default='Learn More', help_text='Call-To-Action Button Text', max_length=20),
        ),
    ]
