# Generated by Django 3.1.8 on 2021-04-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210428_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='cta_btn_text',
            field=models.CharField(blank=True, default='Learn Moree', help_text='Call-To-Action Button Text', max_length=20),
        ),
    ]
